from __future__ import annotations

import json
import sys
from datetime import datetime
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parents[1]
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from app.data.mock_seed import MOCK_DRIVERS

FLEET_ID = "fleet_demo"
DISPATCHER_ID = "DSP001"
DISPATCHER_NAME = "Sauron Dispatch"
DISPATCHER_EMAIL = "dispatch@sauron.local"
SEED_TIMESTAMP = "2026-04-18T12:00:00Z"


def sql_text(value: str | None) -> str:
    if value is None:
        return "null"
    return "'" + value.replace("'", "''") + "'"


def sql_json(value: dict | list | None) -> str:
    if value is None:
        return "null"
    return sql_text(json.dumps(value, separators=(",", ":"))) + "::jsonb"


def split_name(full_name: str) -> tuple[str, str]:
    parts = full_name.split(" ", 1)
    if len(parts) == 1:
        return parts[0], ""
    return parts[0], parts[1]


def map_driver_status(mock_status: str) -> str:
    if mock_status == "idle":
        return "available"
    if mock_status == "driving":
        return "driving"
    if mock_status == "off_duty":
        return "off_duty"
    return "unavailable"


def consignment_status_for_driver(driver: dict) -> str:
    if not driver.get("current_load"):
        return "unassigned"
    if driver["status"] == "driving":
        return "in_transit"
    return "assigned"


def assignment_status_for_driver(driver: dict) -> str:
    if not driver.get("current_load"):
        return "planned"
    if driver["status"] == "driving":
        return "active"
    return "planned"


def parse_iso8601(value: str | None) -> str | None:
    if not value:
        return None
    return datetime.fromisoformat(value.replace("Z", "+00:00")).isoformat().replace("+00:00", "Z")


def build_seed_sql() -> str:
    statements: list[str] = []

    statements.append("-- Generated by backend/scripts/generate_operational_seed_sql.py")
    statements.append("begin;")
    statements.append(
        "insert into dispatcher_profiles (dispatcher_id, fleet_id, name, email, created_at, updated_at) "
        f"values ({sql_text(DISPATCHER_ID)}, {sql_text(FLEET_ID)}, {sql_text(DISPATCHER_NAME)}, "
        f"{sql_text(DISPATCHER_EMAIL)}, {sql_text(SEED_TIMESTAMP)}, {sql_text(SEED_TIMESTAMP)}) "
        "on conflict (dispatcher_id) do update set updated_at = excluded.updated_at;"
    )

    for index, driver in enumerate(MOCK_DRIVERS, start=1):
        first_name, last_name = split_name(driver["name"])
        truck = driver["vehicle"]
        location = driver["location"]
        hos = driver["hos"]
        economics = driver["economics"]
        current_load = driver.get("current_load")

        driver_status = map_driver_status(driver["status"])
        driver_license = f"LIC-{driver['driver_id']}"
        home_terminal = f"{location['city']}, {location['state']}"
        truck_id = truck["vehicle_id"]
        truck_capacity = current_load["weight_lbs"] if current_load else None
        assignment_id = f"ASN{index:03d}" if current_load else None
        consignment_id = f"CON{index:03d}" if current_load else None
        route_plan_id = f"RTE{index:03d}" if current_load else None
        check_in_event_id = f"CHK{index:03d}"
        certification_id = f"CERT{index:03d}"

        statements.append(
            "insert into driver_profiles (driver_id, fleet_id, dispatcher_id, first_name, last_name, phone, "
            "license_number, home_terminal, status, last_known_location, last_check_in_at, current_assignment_id, "
            "created_at, updated_at) values ("
            f"{sql_text(driver['driver_id'])}, {sql_text(FLEET_ID)}, {sql_text(DISPATCHER_ID)}, "
            f"{sql_text(first_name)}, {sql_text(last_name)}, null, {sql_text(driver_license)}, "
            f"{sql_text(home_terminal)}, {sql_text(driver_status)}, {sql_json(location)}, "
            f"{sql_text(hos['last_rest_end'])}, null, {sql_text(SEED_TIMESTAMP)}, "
            f"{sql_text(SEED_TIMESTAMP)}) "
            "on conflict (driver_id) do update set updated_at = excluded.updated_at;"
        )

        statements.append(
            "insert into driver_certifications (certification_id, fleet_id, driver_id, certification_type, notes, "
            "created_at, updated_at) values ("
            f"{sql_text(certification_id)}, {sql_text(FLEET_ID)}, {sql_text(driver['driver_id'])}, "
            f"{sql_text('cdl_class_a')}, {sql_text('Seeded from mock fleet snapshot')}, "
            f"{sql_text(SEED_TIMESTAMP)}, {sql_text(SEED_TIMESTAMP)}) "
            "on conflict (certification_id) do update set updated_at = excluded.updated_at;"
        )

        statements.append(
            "insert into truck_profiles (truck_id, fleet_id, truck_number, vin, make, model, year, capacity_lbs, "
            "current_driver_id, current_assignment_id, last_known_location, created_at, updated_at) values ("
            f"{sql_text(truck_id)}, {sql_text(FLEET_ID)}, {sql_text(driver['truck_number'])}, null, "
            f"{sql_text(truck['make'])}, {sql_text(truck['model'])}, {truck['year']}, "
            f"{'null' if truck_capacity is None else truck_capacity}, {sql_text(driver['driver_id'])}, "
            f"null, {sql_json(location)}, {sql_text(SEED_TIMESTAMP)}, "
            f"{sql_text(SEED_TIMESTAMP)}) "
            "on conflict (truck_id) do update set updated_at = excluded.updated_at;"
        )

        if not current_load:
            statements.append(
                "insert into check_in_events (check_in_event_id, fleet_id, assignment_id, driver_id, truck_id, "
                "checked_in_at, source, location, notes, created_at, updated_at) values ("
                f"{sql_text(check_in_event_id)}, {sql_text(FLEET_ID)}, null, "
                f"{sql_text(driver['driver_id'])}, {sql_text(truck_id)}, {sql_text(SEED_TIMESTAMP)}, "
                f"{sql_text('mock_seed')}, {sql_json(location)}, {sql_text('Initial seeded check-in from mock snapshot')}, "
                f"{sql_text(SEED_TIMESTAMP)}, {sql_text(SEED_TIMESTAMP)}) "
                "on conflict (check_in_event_id) do update set updated_at = excluded.updated_at;"
            )
            continue

        consignment_status = consignment_status_for_driver(driver)
        assignment_status = assignment_status_for_driver(driver)
        requested_pickup_at = hos["last_rest_end"]
        promised_delivery_at = parse_iso8601(current_load["eta"])
        route_stop_pickup_id = f"RST{index:03d}A"
        route_stop_dropoff_id = f"RST{index:03d}B"
        transit_event_id = f"ITE{index:03d}"
        reconciliation_event_id = f"REC{index:03d}"

        statements.append(
            "insert into consignments (consignment_id, fleet_id, customer_reference, shipper_name, receiver_name, "
            "origin, destination, cargo_description, weight_lbs, status, requested_pickup_at, promised_delivery_at, "
            "assigned_driver_id, assigned_truck_id, current_assignment_id, created_at, updated_at) values ("
            f"{sql_text(consignment_id)}, {sql_text(FLEET_ID)}, {sql_text(current_load['load_id'])}, "
            f"{sql_text('Mock Shipper')}, {sql_text('Mock Receiver')}, {sql_text(current_load['origin'])}, "
            f"{sql_text(current_load['destination'])}, {sql_text(current_load['cargo'])}, {current_load['weight_lbs']}, "
            f"{sql_text(consignment_status)}, {sql_text(requested_pickup_at)}, {sql_text(promised_delivery_at)}, "
            f"{sql_text(driver['driver_id'])}, {sql_text(truck_id)}, null, "
            f"{sql_text(SEED_TIMESTAMP)}, {sql_text(SEED_TIMESTAMP)}) "
            "on conflict (consignment_id) do update set updated_at = excluded.updated_at;"
        )

        statements.append(
            "insert into assignments (assignment_id, fleet_id, consignment_id, dispatcher_id, driver_id, truck_id, "
            "status, assigned_at, dispatched_at, notes, created_at, updated_at) values ("
            f"{sql_text(assignment_id)}, {sql_text(FLEET_ID)}, {sql_text(consignment_id)}, {sql_text(DISPATCHER_ID)}, "
            f"{sql_text(driver['driver_id'])}, {sql_text(truck_id)}, {sql_text(assignment_status)}, "
            f"{sql_text(requested_pickup_at)}, {sql_text(requested_pickup_at)}, "
            f"{sql_text('Seeded from mock current_load snapshot')}, {sql_text(SEED_TIMESTAMP)}, "
            f"{sql_text(SEED_TIMESTAMP)}) "
            "on conflict (assignment_id) do update set updated_at = excluded.updated_at;"
        )

        statements.append(
            "insert into route_plans (route_plan_id, fleet_id, assignment_id, status, planned_departure_at, "
            "planned_arrival_at, created_at, updated_at) values ("
            f"{sql_text(route_plan_id)}, {sql_text(FLEET_ID)}, {sql_text(assignment_id)}, "
            f"{sql_text('active' if assignment_status == 'active' else 'approved')}, "
            f"{sql_text(requested_pickup_at)}, {sql_text(promised_delivery_at)}, "
            f"{sql_text(SEED_TIMESTAMP)}, {sql_text(SEED_TIMESTAMP)}) "
            "on conflict (route_plan_id) do update set updated_at = excluded.updated_at;"
        )

        statements.append(
            f"update driver_profiles set current_assignment_id = {sql_text(assignment_id)}, "
            f"updated_at = {sql_text(SEED_TIMESTAMP)} where driver_id = {sql_text(driver['driver_id'])};"
        )

        statements.append(
            f"update truck_profiles set current_assignment_id = {sql_text(assignment_id)}, "
            f"updated_at = {sql_text(SEED_TIMESTAMP)} where truck_id = {sql_text(truck_id)};"
        )

        statements.append(
            f"update consignments set current_assignment_id = {sql_text(assignment_id)}, "
            f"updated_at = {sql_text(SEED_TIMESTAMP)} where consignment_id = {sql_text(consignment_id)};"
        )

        statements.append(
            "insert into check_in_events (check_in_event_id, fleet_id, assignment_id, driver_id, truck_id, "
            "checked_in_at, source, location, notes, created_at, updated_at) values ("
            f"{sql_text(check_in_event_id)}, {sql_text(FLEET_ID)}, {sql_text(assignment_id)}, "
            f"{sql_text(driver['driver_id'])}, {sql_text(truck_id)}, {sql_text(SEED_TIMESTAMP)}, "
            f"{sql_text('mock_seed')}, {sql_json(location)}, {sql_text('Initial seeded check-in from mock snapshot')}, "
            f"{sql_text(SEED_TIMESTAMP)}, {sql_text(SEED_TIMESTAMP)}) "
            "on conflict (check_in_event_id) do update set updated_at = excluded.updated_at;"
        )

        statements.append(
            "insert into route_plan_stops (route_plan_stop_id, route_plan_id, sequence, stop_type, location_name, "
            "planned_arrival_at, planned_departure_at, created_at, updated_at) values ("
            f"{sql_text(route_stop_pickup_id)}, {sql_text(route_plan_id)}, 1, {sql_text('pickup')}, "
            f"{sql_text(current_load['origin'])}, {sql_text(requested_pickup_at)}, {sql_text(requested_pickup_at)}, "
            f"{sql_text(SEED_TIMESTAMP)}, {sql_text(SEED_TIMESTAMP)}) "
            "on conflict (route_plan_stop_id) do update set updated_at = excluded.updated_at;"
        )

        statements.append(
            "insert into route_plan_stops (route_plan_stop_id, route_plan_id, sequence, stop_type, location_name, "
            "planned_arrival_at, created_at, updated_at) values ("
            f"{sql_text(route_stop_dropoff_id)}, {sql_text(route_plan_id)}, 2, {sql_text('dropoff')}, "
            f"{sql_text(current_load['destination'])}, {sql_text(promised_delivery_at)}, "
            f"{sql_text(SEED_TIMESTAMP)}, {sql_text(SEED_TIMESTAMP)}) "
            "on conflict (route_plan_stop_id) do update set updated_at = excluded.updated_at;"
        )

        statements.append(
            "insert into in_transit_events (in_transit_event_id, fleet_id, assignment_id, consignment_id, driver_id, "
            "truck_id, event_type, occurred_at, location, details, created_at, updated_at) values ("
            f"{sql_text(transit_event_id)}, {sql_text(FLEET_ID)}, {sql_text(assignment_id)}, {sql_text(consignment_id)}, "
            f"{sql_text(driver['driver_id'])}, {sql_text(truck_id)}, {sql_text('position_report')}, "
            f"{sql_text(SEED_TIMESTAMP)}, {sql_json(location)}, "
            f"{sql_json({'speed_mph': location['speed_mph'], 'heading': location['heading'], 'source': 'mock_seed'})}, "
            f"{sql_text(SEED_TIMESTAMP)}, {sql_text(SEED_TIMESTAMP)}) "
            "on conflict (in_transit_event_id) do update set updated_at = excluded.updated_at;"
        )

        statements.append(
            "insert into reconciliation_events (reconciliation_event_id, fleet_id, consignment_id, assignment_id, "
            "event_date, status, cost_delta_usd, revenue_delta_usd, details, created_at, updated_at) values ("
            f"{sql_text(reconciliation_event_id)}, {sql_text(FLEET_ID)}, {sql_text(consignment_id)}, {sql_text(assignment_id)}, "
            f"{sql_text(SEED_TIMESTAMP)}, {sql_text('matched')}, 0, {economics['revenue_today']}, "
            f"{sql_json({'cost_per_mile': economics['cost_per_mile'], 'miles_today': economics['miles_today'], 'idle_cost_today': economics['idle_cost_today']})}, "
            f"{sql_text(SEED_TIMESTAMP)}, {sql_text(SEED_TIMESTAMP)}) "
            "on conflict (reconciliation_event_id) do update set updated_at = excluded.updated_at;"
        )

    statements.append("commit;")
    return "\n".join(statements) + "\n"


if __name__ == "__main__":
    print(build_seed_sql(), end="")
